# Generated by Django 3.0.3 on 2020-04-01 05:23

import uuid

from django.db import migrations, models

import books.helpers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='Title Slug')),
                ('author', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover', models.ImageField(blank=True, upload_to=books.helpers.UniqueFilePath(
                    models.SlugField(blank=True, max_length=300, verbose_name='Title Slug')))),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
