# Generated by Django 3.0.3 on 2020-03-24 06:23

from django.db import migrations, models

import books.helpers


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0003_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to=books.helpers.UniqueFilePath(
                models.SlugField(blank=True, max_length=300, verbose_name='Title Slug'))),
        ),
    ]
