# Generated by Django 3.0.3 on 2020-03-24 06:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('orders', '0002_delete_customerorderproduct'),
        ('books', '0004_auto_20200324_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items',
                                               to='orders.CustomerOrder')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
