# Generated by Django 3.0.3 on 2020-03-27 05:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0004_auto_20200324_0623'),
        ('orders', '0002_delete_customerorderproduct'),
        ('order_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.Book')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items',
                                               to='orders.CustomerOrder')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerOrderProduct',
        ),
    ]
