# Generated by Django 3.0.3 on 2020-04-01 05:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_status', models.CharField(
                    choices=[('PND', 'Pending'), ('PAD', 'PAID'), ('AWD', 'AWAITING DELIVERY'), ('DLD', 'DELIVERED')],
                    default='PND', max_length=3)),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Order Date')),
                ('order_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
    ]
