# Generated by Django 3.0.3 on 2020-04-01 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='customer_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orders',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='payment_for_order', to='payments.CustomerPayment'),
        ),
    ]
