# Generated by Django 3.0.3 on 2020-03-24 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerOrderProduct',
        ),
    ]
