# Generated by Django 3.0.3 on 2020-03-27 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0001_initial'),
        ('orders', '0003_auto_20200327_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='payment_for_order', to='payments.CustomerPayment'),
        ),
    ]
